site_name: Mi Bóveda de Obsidian
docs_dir: 'docs'

theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - nl2br
  - obsidian_callouts
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: chart
          class: mkdocs-chart
          format: !!python/name:obsidian_charts_mkdocs.fence_chart

extra_css:
  - stylesheets/quiz.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/quiz.js
  - javascripts/chart.umd.min.js
  - javascripts/charts.js
  - javascripts/evaluador_web.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js